{
 "title": "PerfGraph Visualisation",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Factorial",
   "type": "stat",
   "description": "Visalisation for Factorial",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(factorial_time_duration_millis_sum) by (nsize) / sum(factorial_time_duration_millis_count) by (nsize)",
     "legendFormat": "{{nsize}}"
    }
   ]
  },
  {
   "title": "Quadratic",
   "type": "barchart",
   "description": "Visualisation for Quadratic TC",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(quadratic_time_duration_millis_sum) by (nsize) / sum(quadratic_time_duration_millis_count) by (nsize)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NlogN",
   "type": "barchart",
   "description": "Visualisation for NlogN",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(nlogn_time_duration_millis_sum) by (nsize) / sum(nlogn_time_duration_millis_count) by (nsize)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Linear",
   "type": "gauge",
   "description": "Visualisation for Linear",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(linear_time_duration_millis_sum) by (nsize) / sum(linear_time_duration_millis_count) by (nsize)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "logN",
   "type": "gauge",
   "description": "Visualisation for logN",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(logn_time_duration_millis_sum) by (nsize) / sum(logn_time_duration_millis_count) by (nsize)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Constant",
   "type": "timeseries",
   "description": "Visualisation for Constant",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(constant_time_duration_millis_sum) by (nsize) / sum(constant_time_duration_millis_count) by (nsize)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}